### ISSUE TITLE
Initial thoughts on using the SDK

### ISSUE THREAD

**Issue by roughpandaz** [sporeprotocol/spore-first-example#1]
### Variable naming
1. Most developers will not know the difference between Secp256k1 vs others... Is it relevant in this demo?
https://github.com/sporeprotocol/spore-first-example/blob/0fd0a79fdbfab06c0d11c08011f457986fa85d93/src/index.ts#L6C18-L6C39

**Idea**
``` js

createSecp256k1Wallet
// Change variable name to
createWallet
```

### Can't see image in explorer
2. After creating a demo Spore - it's unclear where the "demo" image is, or it's not possible to view it from the explorer
https://pudge.explorer.nervos.org/transaction/0x34ff903714263fe45678506314f3f7e17e2128ccebd6b1cb8464e7b5b0464c2a

<img width="1416" alt="Screenshot 2023-09-23 at 6 10 38 PM" src="https://github.com/sporeprotocol/spore-first-example/assets/3782456/ead3f546-dde1-4776-8a59-6f5e1e339fc0">

**Idea**
Enable viewing of images on the explorer OR create simple website to view deployed Spores.

### Show transaction fees
3. Currently, it's unclear how the transaction fees were paid. 
**Idea**
Can we explain to users how much this transaction costs.

**Comment by ShookLyngs** [comment]
Thanks for your feedback, I have some additional thoughts:

### 1. Variable naming

I agree with the idea of ​​simplifying the concepts presented in the example. But I disagree with the "remove the concept of Lock Script" part, I think it's important to carry the concept of Lock Script in the code example. 

Maybe we can find a better way to solve it, for example, can we humanize the lock's name:
```
createSecp256k1Wallet -> createDefaultLockWallet
```

### 2. Can't see image in explorer

True, maybe we can:
- Request CKB Explorer to improve the visualization of spores
- Develop a Spore Ecological Garden app that supports visualization of various MIME types

Some fallback solutions, FYI:
- Visit spore-demo to view image/text spores: 
  https://a-simple-demo.spore.pro/spore/0xd7ab1a86a745afb5e60ba2b38ce963379506c66038fc6ae11518188e59761d7e
- If the spore belongs to any cluster, visit the cluster on CKB Explorer: 
  https://pudge.explorer.nervos.org/nft-collections/0x8448ba5f8d98d141d2c00fb860922bca50850e4de99b5ca51e6534cb1f2e0c40?tab=inventory

### 3. Show transaction fees

You're right, this is a widely requested feature. 
Maybe we should provide fee usage info in the return value of Composed APIs.

**Comment by ShookLyngs** [comment]
Opened a PR to solve the "Variable naming" issue:
- https://github.com/sporeprotocol/spore-first-example/pull/2

**Comment by ashuralyk** [comment]
@ShookLyngs can this issue be closed?
